import pandas

test = pandas.read_csv(r'E:\dataset\user_insta.csv')
test['0'] = test['appCategory'].apply(lambda x: [0, 1][x == 0])
test['1'] = test['appCategory'].apply(lambda x: [0, 1][x == 1])
test['2'] = test['appCategory'].apply(lambda x: [0, 1][x == 2])
test['101'] = test['appCategory'].apply(lambda x: [0, 1][x == 101])
test['103'] = test['appCategory'].apply(lambda x: [0, 1][x == 103])
test['104'] = test['appCategory'].apply(lambda x: [0, 1][x == 104])
test['105'] = test['appCategory'].apply(lambda x: [0, 1][x == 105])
test['106'] = test['appCategory'].apply(lambda x: [0, 1][x == 106])
test['108'] = test['appCategory'].apply(lambda x: [0, 1][x == 108])
test['109'] = test['appCategory'].apply(lambda x: [0, 1][x == 109])
test['110'] = test['appCategory'].apply(lambda x: [0, 1][x == 110])
test['201'] = test['appCategory'].apply(lambda x: [0, 1][x == 201])
test['203'] = test['appCategory'].apply(lambda x: [0, 1][x == 203])
test['204'] = test['appCategory'].apply(lambda x: [0, 1][x == 204])
test['209'] = test['appCategory'].apply(lambda x: [0, 1][x == 209])
test['210'] = test['appCategory'].apply(lambda x: [0, 1][x == 210])
test['211'] = test['appCategory'].apply(lambda x: [0, 1][x == 211])
test['301'] = test['appCategory'].apply(lambda x: [0, 1][x == 301])
test['303'] = test['appCategory'].apply(lambda x: [0, 1][x == 303])
test['401'] = test['appCategory'].apply(lambda x: [0, 1][x == 401])
test['402'] = test['appCategory'].apply(lambda x: [0, 1][x == 402])
test['403'] = test['appCategory'].apply(lambda x: [0, 1][x == 403])
test['405'] = test['appCategory'].apply(lambda x: [0, 1][x == 405])
test['406'] = test['appCategory'].apply(lambda x: [0, 1][x == 406])
test['407'] = test['appCategory'].apply(lambda x: [0, 1][x == 407])
test['408'] = test['appCategory'].apply(lambda x: [0, 1][x == 408])
test['409'] = test['appCategory'].apply(lambda x: [0, 1][x == 409])
test['503'] = test['appCategory'].apply(lambda x: [0, 1][x == 503])
test = test.drop('appCategory', axis=1)
test = test.groupby(['userID'], as_index=False).sum()
test.to_csv(r'E:\dataset\user_install3.csv', index=False, sep=',')
print 'successfully'